### ISSUE TITLE
What's the advantage of this project compared to other framework like Dify

### ISSUE THREAD

**Issue by MooMooHorse** [CosmosShadow/GeneralAgent#10]
I saw the 4 features listed, and it seems like they are a subset of [Dify](https://github.com/langgenius/dify). This makes me curious about the motivation. I briefly looked at the paper and it seems the highlight is self-call and stack memory. Can you explain why these 2 things are important?

**Comment by CosmosShadow** [comment]
This is a Agent Framework, not LLM application/workflow platform.
