### ISSUE TITLE
new_llm_inference 怎么写，可以给个例子吗？

### ISSUE THREAD

**Issue by ageekor** [CosmosShadow/GeneralAgent#12]
from GeneralAgent import skills
def new_llm_inference(messages, model, stream=False, temperature=None, api_key=None, base_url=None):
    """
    使用大模型进行推理
    """
    pass
skills.llm_inference = new_llm_inference
new_llm_inference 怎么写，可以给个例子吗？

**Comment by ageekor** [comment]
what to return?

**Comment by CosmosShadow** [comment]
参考 GeneralAgent/skills/llm_inference.py 文件中 llm_inference 函数.
