### ISSUE TITLE
python interpreter调用死循环

### ISSUE THREAD

**Issue by trundleyrg** [CosmosShadow/GeneralAgent#18]
https://github.com/CosmosShadow/GeneralAgent/blob/34b2a5e7cbb53f67a87a3efed116267d11df6576/GeneralAgent/interpreter/python_interpreter.py#L147

这一行这判断和注释对不上，是否应该改成
```
stop = self.agent.run_level == 1
```

**Comment by jayceftg** [comment]
是的，感谢，已修改。
