### ISSUE TITLE
'NoneType' object is not callable

### ISSUE THREAD

**Issue by sharejing** [CosmosShadow/GeneralAgent#4]
![image](https://github.com/CosmosShadow/GeneralAgent/assets/33115703/fab58723-cfe1-4301-86d0-98be4a48c233)

Openai API key has been configured, but it still cannot be returned correctly

**Comment by CosmosShadow** [comment]
Please Hold on, there will be a new release.

**Comment by CosmosShadow** [comment]
Please use the v0.2.0 version.

**Comment by CosmosShadow** [comment]
close.
