### ISSUE TITLE
能否支持国内的大模型，如何配置？

### ISSUE THREAD

**Issue by albertyou2** [CosmosShadow/GeneralAgent#5]
能否支持国内的大模型，如何配置？

**Comment by CosmosShadow** [comment]
目前直接兼容OpenAI大模型格式的国产大模型，在环境变量(.env)文件中，填写 OPENAI_API_KEY 和 OPENAI_API_BASE 为国产大模型的参数就可以了。

**Comment by CosmosShadow** [comment]
具体可以参考: https://github.com/CosmosShadow/GeneralAgent/blob/main/examples/8_multi_model.py
