### ISSUE TITLE
Do not support Azure Open AI.

### ISSUE THREAD

**Issue by JunweiDuan** [CosmosShadow/GeneralAgent#8]
Traceback (most recent call last):
  File "D:\Users\--\AppData\Roaming\Python\Python311\site-packages\GeneralAgent\agent\agent.py", line 310, in _llm_and_parse_output
    for token in response:
  File "D:\Users\--\AppData\Roaming\Python\Python311\site-packages\GeneralAgent\skills\llm_inference.py", line 121, in _llm_inference_with_stream
    raise ValueError('LLM(Large Languate Model) error, Please check your key or base_url, or network')
ValueError: LLM(Large Languate Model) error, Please check your key or base_url, or network

**Comment by Okysu** [comment]
#2 可以查看这个PR

**Comment by JunweiDuan** [comment]
我后来自己改了下支持Azure Open AI了：

def _get_openai_client(api_key=None, base_url=None):
    from openai import AzureOpenAI
    import os
    if api_key is None and 'OPENAI_API_KEY' not in os.environ:
        raise ValueError('Please set OPENAI_API_KEY in environment')
    api_key = api_key or os.environ['OPENAI_API_KEY']
    base_url = base_url or os.environ.get('OPENAI_API_BASE', 'https://api.openai.com/v1')
    api_version = os.environ.get('OPENAI_API_VERSION')
    client = AzureOpenAI(api_key=api_key, azure_endpoint=base_url, max_retries=3, api_version=api_version)
    return client
